---
title: "CS 422 Homework 8"
author: "Xingli Li"
output:
  html_notebook: 
    toc: yes
    toc_float: yes
    toc_depth: 5
  html_document:
    toc: yes
    df_print: paged
editor_oprions:
  markdown:
    wrap: 100
---

## Homework 8

### Part 2

set work space and install dependent package.

```{r}
library(cluster)
library(factoextra)
setwd(getwd())
```

```{r}
rm(list=ls())

data(iris)

names(iris)

x <- iris[,1:4]
y <- iris$Species

# Scale the data
d <- scale(iris[,1:4])

kc <- kmeans(x,3)

kc
```

```{r}
table(y,kc$cluster)
```

```{r}
plot(x[c("Sepal.Length", "Sepal.Width")], col=kc$cluster)
points(kc$centers[,c("Sepal.Length", "Sepal.Width")], col=1:3, pch=23, cex=3)
```

```{r}

hc.complete <- hclust(dist(d), method="complete")

# A colorful plot
fviz_dend(hc.complete, show_labels=T, palette = "jco",
          main="HCLUST (Complete Linkage)", k=3)

# Default plot --- utilitarian, but serves the purpose.
plot(hc.complete)

# Cut at around Height = 5 to get 3 clusters, or
clusters.3 <- cutree(hc.complete, 3)
table(clusters.3)
table(iris$Species)
# Clearly, one can improve the clustering to get better classification.

hc.single <- hclust(dist(d), method="single")
fviz_dend(hc.single, show_labels=T, palette = "jco",
          main="HCLUST (Single Linkage)", k=3)
# Not quite sure where to cut to get 3 clusters.
```
