---
title: "CS 422 HW10"
author: "Wenjing Wang"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float: yes
---


### Part 1
```{r}
library(lsa)
library(data.table)
setwd("/media/eric/Data/IIT/CS422/cs422_hw/assignment10-XIngli-Li/ml-latest-small")
userdf<-fread("ratings.csv")
movie<-fread("movies.csv")
movie
userdf211<-userdf[(28336:28390),]
userdf211
moviedf<-movie[(userdf211$movieId),]
moviedf
```
```{r}
a<-strsplit(moviedf$genres,split = "|",fixed = TRUE)
a
```
```{r}
user0 <- data.frame(matrix(ncol = 20, nrow = 55))
x <- c("Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy","Film-Noir","Horror","IMAX","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Wester","(no genres listed)")
colnames(user0) <- x
movieId<-moviedf$movieId
user1<-cbind(movieId, user0)
user1
```

```{r}
for (i in 1:55)
        for(k in a[i])
                for (j in 2:21)
                        ifelse(k==colnames(user1)[j], user1[i,j]<-1, k)
user1
```
```{r}
user1[nrow(user1)+1,]<-NA
user1
```
```{r}
user1[56,1]<-"AVG"
user1[is.na(user1)] <- 0
user1
for (n in 2:21)
        user1[56,n]<-mean(user1[1:55,n])
user11<-user1[56,2:21]
userprofile<-as.vector(t(user11))
userprofile
```

```{r}
b<-strsplit(movie$genres,split = "|",fixed = TRUE)
```
```{r}
user00<- data.frame(matrix(ncol = 21, nrow = 9125))
y <- c("movieId","Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy","Film-Noir","Horror","IMAX","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Wester","(no genres listed)")
colnames(user00) <- y
user00$movieId<-movie$movieId
user00
```
```{r}
for (i in 1:9125) for(k in b[i]) for (j in 2:21) ifelse(k==colnames(user00)[j], user00[i,j]<-1, k)
user00
user00[is.na(user00)] <- 0
user00
```

```{r}
movieprofile<-function(movieID){
  temp_C<-as.vector(t(user00[(movieID-1),2:21]))
  return(temp_C)
  }
```

```{r}
movieprofile(44)
```
```{r}
cosine(userprofile,movieprofile(44))
```
```{r}
main<-function(userID,random10){
  # userID<-211
  # set.seed(100)
  # random10 <- as.vector(c(t(sample(movie$movieId,10))))
  random10str <- ""
  
  df <- data.frame(MovieId=0,MovieName="",Similarity=0)
  
  test.lenght<- length(random10)
  n <- 1
  
  for (i in random10){
    
    similarity <- cosine(userprofile, movieprofile(i))
    
    title <- movie$title[movie$movieId==i]
    movieId <- movie$movieId[movie$movieId==i]
    row <- data.frame(MovieId=movieId,MovieName=title,Similarity=similarity)
    df <- rbind(df,row)
    
    random10str <- paste0(random10str,movieId)
    random10str<-ifelse(n!=test.lenght,paste0(random10str,","),random10str)
    n=n+1
  }
  
  print(paste("User ID 211 chose the following 10 movies:",random10str, "of these, the following 5 movies are recommended:"))
  
  df <- df[-1,]
  df_sorted <- df[order(df$Similarity,decreasing = TRUE),]
  df_sorted[1:5,]

}

```



```{r}
main(211,c(5612,943,7358,25,2108,8371,2699,8923,2487,102800))
```
