---
title: "CS 422 Homework 3"
author: "Xingli Li"
output: html_notebook
toc: yes
toc_float: yes
---

## Homework 3

set work space and install dependent package.

```{r}

setwd(getwd())

library(rpart)  #classification and regression trees
library(rpart.plot)
#library(partykit) #treeplots
```

Building Decision Tree on the Iris Dataset

```{r }

names(iris)

count.train <-NROW(iris)

df.train <- iris[1:count.train,]
df.train.x <- df.train[,1:4]
df.train.y <- df.train[,5]
```

```{r }

## xval: 10 fold cross validation
## minsplit: the minimum number of branch nodes. If it is greater than or equal to 20, the node will continue to divide, otherwise it will stop.
## minbucket：Minimum samples of leaf nodes. 

model <- rpart(Species ~ ., data = df.train, method="class")

#summary(model)

# plot method of the partykit package.
# plot(as.party(model))

rpart.rules(model,cover = TRUE)

## printcp() will tell you how much CP value is divided into each layer and what the average relative error is.
printcp(model)
# cp: complexity parameter of the node.
# nsplit: Number of tree splits.
# rel error: Relative error = xerror ± xstd.
# xerror: Estimation error of cross validation.
# xstd: Standard deviation of cross validation process.
```

```{r}
# Drawing decision classification tree
rpart.plot(model, extra=104, fallen.leaves=T, type=4,
           main="Iris Dataset Decision Tree") 

## chose the value of CP with the smallest xerror.
# cp <- model$cptable[which.min(model$cptable[,"xerror"]),"CP"]
                    
## Pruning
#model.pruned <- prune(model, cp= cp)  

# Redrawn
# rpart.plot(model.pruned, extra=104, fallen.leaves=T, type=4, main="Iris Dataset Decision Tree")
```
